### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by zgababa** [json-schema-faker/json-schema-faker#551]
Hey ! 

The current release v0.5.0-rc24 0.5.0-rc24 has the pipeline failing, and I suspect that the code we get from the package is not rightly built. 

Thanks !

**Comment by pateketrueke** [comment]
Oh, it's not critical, most time a single test on CI fails due network connectivity, so I think it's fin to ignore it and re-run CI to make it green.

Later I'll be changing such test with something more reliable, thank you! 🍻

**Comment by zgababa** [comment]
Hum, I think the problem is more complex.

When I install the 0.5.0-rc24, I have this 

![image](https://user-images.githubusercontent.com/3789044/72071075-41bf9780-32eb-11ea-997e-bdbffe9631e3.png)

With 0.5.0-rc23 I have this : 
![image](https://user-images.githubusercontent.com/3789044/72071211-8f3c0480-32eb-11ea-84f6-d124d2611828.png)

So when I run my tests with the 0.5.0-rc24, I have this error : 
![image](https://user-images.githubusercontent.com/3789044/72071259-aa0e7900-32eb-11ea-969a-0d60676b4819.png)

Thanks !

**Comment by pateketrueke** [comment]
Gotcha, gonna fix that asap! 🔥

**Comment by pateketrueke** [comment]
Fixed in `0.5.0-rc24.0` 💣

**Comment by zgababa** [comment]
Thanks, but it looks still the same :/

The `generate` method has disappear, and the `dist` folder too. Only in the rc23 there is `dist` folder not  from the `rc24`

Thanks !

**Comment by zgababa** [comment]
Hey ! 

Why the npm version is still `0.5.0-rc23`. 
We have to do `yarn add json-schema-faker@next ` to have the correct version.

Thanks :)

**Comment by pateketrueke** [comment]
Yeah, I've been trying to pre-release `0.5.0-rc24.0` but the final tag may change, so using `next` is fine while I'm still working on it.
